# Generated by Django 4.0 on 2021-12-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='phone number'),
        ),
    ]
