# Generated by Django 4.0 on 2021-12-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_newuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('content', models.CharField(max_length=7000, verbose_name='content')),
                ('visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('files', models.FileField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x00000184F55FF100>')),
                ('sequence_time', models.DateTimeField(auto_now=True)),
                ('replay_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.newuser')),
            ],
        ),
    ]
